### ISSUE TITLE
Enhancement: Allow setting the end date to be same as the due date

### ISSUE THREAD

**Issue by BenD10** [an-algonquin-facilitator/assistant#1]
Hi, this repo is great, thank you!

Typically for my courses, I have the due date and end date set to the exact same (e.g. September 16th at 11:59PM). Is it possible to support this workflow?

**Comment by hydroflame** [comment]
Broke in commit ea26bcd272826e47ebb83da7d5591866bca5aec4
Fixed in commit aeff77cecb78d9aa74c68ffbd395e2df426a8f5b
Due dates and End Dates are always supposed to be end of day, start date the start of the day.
